In [1]:
import numpy as np

In [3]:
# Membuat Tensor
tensor=np.array([
                [[23,50,7,12],[75,21,57,12]],
                [[57,56,99,43],[87,26,18,84]]])
print(tensor)

[[[23 50  7 12]
  [75 21 57 12]]

 [[57 56 99 43]
  [87 26 18 84]]]


In [21]:
#perkalian matrix
A=np.array([[23,50,19],[7,12,109],[57,67,98]])
B=np.array([17,22,19])

print(A*B)

[[ 391 1100  361]
 [ 119  264 2071]
 [ 969 1474 1862]]


In [19]:
A=np.array([[23,50,19],
            [7,12,109],
            [57,67,98]])

In [23]:
# Tranpose
print(A.T)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [25]:
# Menghitung Determinan
print(np.linalg.det(A))

131344.0000000002


In [26]:
#invers
print(np.linalg.inv(A))

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
